Description of check_past_exist
Home > SeqROCTM > tools > check_past_exist.m
check_past_exist
PURPOSE
Check if a past sequence can be generated by a CTM.
SYNOPSIS
exist = check_past_exist(past, contexts, P)
DESCRIPTION
CHECK_PAST_EXIST Check if a past sequence can be generated by a CTM.
 Inputs
 past      : past sequence to be checked
 contexts  : context tree
 P         : transition probabilities (each row is the distribution of a context)
 Output
 exist     : 1 if the sequence can be generated by the model, 0 otherwise
Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
Date   : 05/2020
CROSS-REFERENCE INFORMATION
This function calls:
check_past_exist Check if a past sequence can be generated by a CTM.
contextfunction Return the context associated to a given (past) sequence.
is_suffix_of_contexts Get all the contexts from which a given sequence is a suffix.
This function is called by:
check_past_exist Check if a past sequence can be generated by a CTM.
contextTree_to_FiniteMarkov Compute the representation of a context tree model as a k-order Markov process.
SOURCE CODE
function exist = check_past_exist(past, contexts, P)
%CHECK_PAST_EXIST Check if a past sequence can be generated by a CTM.
%
% Inputs
%
% past      : past sequence to be checked
% contexts  : context tree
% P         : transition probabilities (each row is the distribution of a context)
%
% Output
%
% exist     : 1 if the sequence can be generated by the model, 0 otherwise
%
%Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
%Date   : 05/2020
L = length(past);
exist = false;
if L == 1
    exist = true;  % for L = 1, always exist
elseif sum(cellfun(@(a) isequal(a, past), contexts, 'Uni', 1)) == 1  %it is a context
    exist = true;
else
    % check if the past with length L-1 exists
    if check_past_exist(past(1 : L-1), contexts, P)
        % check if the transition of symbol in position L, given the past, exists
        % looks if there exist a context associated to the past
        [~, i_context] = contextfunction(past(1:L-1), contexts);
        if (i_context ~= -1) % if there exist
            if (P(i_context, past(L)) > 0) % check if the transition is possible
                exist = true;
            end
        else
            % if there is no context associated to the past, find the
            % contexts from which this past is a suffix
            [~, index] = is_suffix_of_contexts(past(1:L-1), contexts);
            j = 1;
            % check if for some of that contexts the transition is possible
            while (~exist)&&(j <= length(index))
                if P(index(j), past(L)) > 0
                    exist = true;
                else
                    j = j + 1;
                end
            end
        end
    end
end