Description of EMC
Home > SeqROCTM > tools > EMC.m
EMC
PURPOSE
Compute the Effective Measure Complexity of a context tree model.
SYNOPSIS
compl = EMC(contexts, P, A)
DESCRIPTION
EMC Compute the Effective Measure Complexity of a context tree model.
 Inputs
  contexts : set of contexts
  P        : transition probabilities associated to the contexts
  A        : alphabet
 Output
  compl    : Effective measure complexity
 Reference:
   Grassberger et. al., International Journal of Theoretical Physics 25, 1986.
Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
Date   : 08/2020
CROSS-REFERENCE INFORMATION
This function calls:
EntropyN Computes the entropy of the distribution of subsequences of length 1,...,N that are generated by a context tree model.
EntropyRateCT Compute the entropy rate of the stochastic process represented by the context tree model.
empprobsubsequences Estimate the probability of occurrences of all the sequences
This function is called by:
SOURCE CODE
function compl = EMC(contexts, P, A)
%EMC Compute the Effective Measure Complexity of a context tree model.
%
% Inputs
%
%  contexts : set of contexts
%  P        : transition probabilities associated to the contexts
%  A        : alphabet
%
% Output
%
%  compl    : Effective measure complexity
%
% Reference:
%   Grassberger et. al., International Journal of Theoretical Physics 25, 1986.
%
%Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
%Date   : 08/2020
order = max(cellfun(@(x) length(x), contexts, 'uniformoutput', 1));
% estimate some probabilities and transition probabilities
[est_P, est_transP, iT] = empprobsubsequences(contexts, P, A);
% get the block entropy
[~, hn] = EntropyN(est_P, est_transP, iT, order);
% get the entropy rate
H = EntropyRateCT(contexts, P, A);
% compute the complexity EMC
compl = 0;
for i = 1 : order
    compl = compl + hn(i) - H;
end
end