Description of transition_context2context
Home > SeqROCTM > tools > transition_context2context.m
transition_context2context
PURPOSE
Gives the possible transitions from contexts to contexts.
SYNOPSIS
Tw = transition_context2context(contexts, P, A)
DESCRIPTION
TRANSITION_CONTEXT2CONTEXT Gives the possible transitions from contexts to contexts.
                           This function creates a cell array of dimension
                           number_of_context x number_of_symbols containing
                           the index of the context(s) that can be generated
                           given a context and a symbol
 Inputs
     contexts : context tree
     P        : transition probabilities
     A        : alphabet
 Outputs
     Tw       : cell array containing the index of the context(s) generated by
              observing a context followed by a symbol. The rows of the matrix indicate
              the context and the columns the symbols in the alphabet
Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
Date   : 04/2020
CROSS-REFERENCE INFORMATION
This function calls:
contextfunction Return the context associated to a given (past) sequence.
is_suffix_of_contexts Get all the contexts from which a given sequence is a suffix.
This function is called by:
tree_renewalpoint Among all the contexts that are renewal points, select the most frequents
SOURCE CODE
function Tw = transition_context2context(contexts, P, A)
%TRANSITION_CONTEXT2CONTEXT Gives the possible transitions from contexts to contexts.
%                           This function creates a cell array of dimension
%                           number_of_context x number_of_symbols containing
%                           the index of the context(s) that can be generated
%                           given a context and a symbol
%
% Inputs
%
%     contexts : context tree
%     P        : transition probabilities
%     A        : alphabet
%
% Outputs
%
%     Tw       : cell array containing the index of the context(s) generated by
%              observing a context followed by a symbol. The rows of the matrix indicate
%              the context and the columns the symbols in the alphabet
%
%Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
%Date   : 04/2020
% number of contexts and symbols
ncontexts = length(contexts);
nsymbols = length(A);
% initialize Tw
Tw = cell(ncontexts, nsymbols);
for w = 1 : ncontexts
    for s = 1 : nsymbols
        if P(w,s) > 0
            str = [contexts{w}, A(s)];
            [~, idx_nextw] = contextfunction(str, contexts);
            if idx_nextw == -1  %if there is no context suffix of ws
                %looks for the context from which w is a suffix
                [~,idx_nextw] = is_suffix_of_contexts(str, contexts);
            end
            Tw{w,s} = idx_nextw;
        end
    end
end
end