Description of tree2nodes
Home > SeqROCTM > tools > tree2nodes.m
tree2nodes
PURPOSE
Gives the set of nodes corresponding to a context tree.
SYNOPSIS
nodes = tree2nodes(tree)
DESCRIPTION
TREE2NODES Gives the set of nodes corresponding to a context tree.
 Inputs
   tree   : a context tree
 Outputs
   nodes  : the set of nodes
Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
Date   : 02/2021
CROSS-REFERENCE INFORMATION
This function calls:
node Class to model a node of a tree
This function is called by:
distance_balding Compute the distance of Balding between two context trees.
get_search_space_trees Compute all the context trees that ccan result from the estimation process (search space).
SOURCE CODE
function nodes = tree2nodes(tree)
%TREE2NODES Gives the set of nodes corresponding to a context tree.
%
% Inputs
%   tree   : a context tree
%
% Outputs
%   nodes  : the set of nodes
%
%Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
%Date   : 02/2021
nodes = {};
%number of contexts
nc = length(tree);
for i = 1 : nc
    %get the context, add it to the set of nodes and add the nodes from it
    %to the root
    node = tree{i};
    while ~isempty(node)
        nodes = [nodes, node];
        node = node(2:end);
    end
end
%delete the repeated nodes
N = cellfun(@(x) num2str(x(:)'), nodes,'UniformOutput', false);
[~, idx] = unique(N);
nodes = nodes(idx);
end