Description of node
Home > SeqROCTM > vizualization > node.m
node
PURPOSE
Class to model a node of a tree
SYNOPSIS
This is a script file.
DESCRIPTION
Class to model a node of a tree
Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
Date   : 02/2024
CROSS-REFERENCE INFORMATION
This function calls:
node Class to model a node of a tree
This function is called by:
CTestimator Estimate a context tree from a sequence or from a SeqROCTM.
estimate_functionalSeqROCTM Estimate a context tree from a SeqROCTM with functional data as elements of the response sequence.
distanceCT Compute a distance between context trees.
distance_balding Compute the distance of Balding between two context trees.
median_tree Compute the median tree from a set of context trees.
mode_tree Computes the mode context tree of a set of context tree.
tree2nodes Gives the set of nodes corresponding to a context tree.
contexts_to_tree Gives a tree class from the list contexts
node Class to model a node of a tree
SUBFUNCTIONS
function obj = node(data, varargin)
function insert_son(obj, n, index)
function add_son(obj, n)
function textstr = print(obj)
SOURCE CODE
%Class to model a node of a tree
%
%Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
%Date   : 02/2024
classdef node < handle
    properties
        data;
        children;
    end
    methods
        %constructor
        function obj = node(data, varargin)
            if nargin > 0
                obj.data = data;
                numvarargs = length(varargin);
                if numvarargs == 1
                    obj.children = varargin{1};
                else
                    obj.children = [];
                end
            end
        end
        %insert a son at a given position
        function insert_son(obj, n, index)
            nl = numel(obj.children);
            new_children(nl+1) = node();
            for ii = 1 : index-1
                new_children(ii) = obj.children(ii);
            end
            new_children(index) = n;
            for ii = index : nl
                new_children(ii+1) = obj.children(ii);
            end
            obj.children = new_children;
        end
        %add a son
        function add_son(obj, n)
            obj.children = [obj.children, n];
        end
        %print to console
        function textstr = print(obj)
            nl = numel(obj.children);
            whiteSpaces = repmat(' ', 1, 2*length(obj.data));
            if nl==0
                textstr = [whiteSpaces, '--(', obj.data, ')', '-*', newline];
            else
                textstr = [whiteSpaces, '--(', obj.data, ')', newline];
                for i = 1 : nl
                    textstr = [textstr, obj.children(i).print];
                end
            end
        end
    end
end