Description of contextfunction
Home > SeqROCTM > tools > contextfunction.m
contextfunction
PURPOSE
Return the context associated to a given (past) sequence.
SYNOPSIS
[c, idx] = contextfunction(past, contexts)
DESCRIPTION
CONTEXTFUNCTION Return the context associated to a given (past) sequence.
 Inputs
     past      : sequence
     contexts  : set of contexts (context tree)
 Outputs
     c         : context associated to the sequence [past]
     idx       : index (position) of the context [c] in [contexts]. If do
               not exist, idx=-1
 Usage
            ctxs = {0, [0 1], [1 1], 2};
            past = [0 1 1 0 1 2 0 1];
            [c, idx] = contextfunction(past, ctxs);
Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
Date   : 05/2020
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
generatesampleCTM Generates a sample of context tree model.
generatesampleYSeqROCTM Generates the response sequence of a SeqROCTM from a sequence of inputs, the context tree and the distributions associated to the contexts.
tuning_risk Model selection using a risk function for a Context tree model.
tuning_risk2 Model selection using a risk function for a SeqROCTM.
check_past_exist Check if a past sequence can be generated by a CTM.
contextTree_to_FiniteMarkov Compute the representation of a context tree model as a k-order Markov process.
dissimilarity_emp Compute a dissimilarity between two probabilistic context tree.
dissimilarity_th Compute a dissimilarity between two probabilistic context tree.
seq2ctx Converts a sequence in the corresponding sequence of indices of contexts.
transition_context2context Gives the possible transitions from contexts to contexts.
SOURCE CODE
function [c, idx] = contextfunction(past, contexts)
%CONTEXTFUNCTION Return the context associated to a given (past) sequence.
%
% Inputs
%
%     past      : sequence
%     contexts  : set of contexts (context tree)
%
% Outputs
%
%     c         : context associated to the sequence [past]
%     idx       : index (position) of the context [c] in [contexts]. If do
%               not exist, idx=-1
%
% Usage
%            ctxs = {0, [0 1], [1 1], 2};
%            past = [0 1 1 0 1 2 0 1];
%            [c, idx] = contextfunction(past, ctxs);
%
%Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
%Date   : 05/2020
n_contexts = length(contexts);
lpast = length(past);
idx = -1;
c = [];
found = false;
i = 0;
while (~found)&&(i < n_contexts)
    i = i + 1;
    li = length(contexts{i});
    found = (li <= lpast) && (isequal(contexts{i},past(end-li+1 : end)));
end
if found
    c = contexts{i};
    idx = i;
end
end