Description of samplediscretedist
Home > SeqROCTM > data_manipulation > samplediscretedist.m
samplediscretedist
PURPOSE
Sample from a discrete distribution.
SYNOPSIS
[xsampled, indices] = samplediscretedist(x, prob, nsamples)
DESCRIPTION
SAMPLEDISCRETEDIST Sample from a discrete distribution.
 Inputs
   x         : domain of the distribution
   prob      : probability associated to each value on x
   nsamples  : number of sampled values
 Outputs
   xsampled  : sampled values
   idx       : index of the sampled values
Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
Date   : 04/2020
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
generatesampleCTM Generates a sample of context tree model.
generatesampleCTM_fast Generates samples of a context tree model.
generatesampleYSeqROCTM Generates the response sequence of a SeqROCTM from a sequence of inputs, the context tree and the distributions associated to the contexts.
SOURCE CODE
function [xsampled, indices] = samplediscretedist(x, prob, nsamples)
%SAMPLEDISCRETEDIST Sample from a discrete distribution.
%
% Inputs
%   x         : domain of the distribution
%   prob      : probability associated to each value on x
%   nsamples  : number of sampled values
%
% Outputs
%   xsampled  : sampled values
%   idx       : index of the sampled values
%
%Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
%Date   : 04/2020
xsampled = zeros(nsamples,1);
indices = zeros(nsamples,1);
% cells in the interval [0,1]
u = cumsum(prob);
% generate samples from a uniform distribution in [0,1]
s = rand(1, nsamples);
% find in which cell of the interval the sample is
for n = 1 : nsamples
    idx = 1;
    while s(n) > u(idx)
        idx = idx + 1;
    end
    xsampled(n) = x(idx);
    indices(n) = idx;
end
end