Description of generatesampleCTM_fast
Home > SeqROCTM > data_manipulation > generatesampleCTM_fast.m
generatesampleCTM_fast
PURPOSE
Generates samples of a context tree model.
SYNOPSIS
B = generatesampleCTM_fast(contexts, P, A, lengthSeq, nsamples)
DESCRIPTION
GENERATESAMPLECTM_FAST Generates samples of a context tree model.
 Inputs
   contexts        : set of contexts
   P               : probability distributions associated to the contexts. Each
                     row contains the distribution of the corresponding context
   A               : Alphabet
   lengthSeq       : length of the sequences to be generated
   nsamples        : number of sequences
 Outputs
   B               : a matrix containing on each row a sequence
 Usage
            A = [0,1,2];
            ctxs = {0, [0 1], [1 1], 2}
            P = [0,   1,   0; ...
                  0,   0.25,   0.75;
                  1,   0,   0;
                  1,   0,   0 ];
            B = generatesampleCTM_fast(ctxs, P, A, 100, 300);
Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
Date   : 04/2020
CROSS-REFERENCE INFORMATION
This function calls:
samplediscretedist Sample from a discrete distribution.
contextTree_to_FiniteMarkov Compute the representation of a context tree model as a k-order Markov process.
This function is called by:
tuningContextTreeModels Examples on tuning procedures.
tune_SeqROCTM Tune a SeqROCTM estimation algorithm.
tune_contextTreeModel Tune a context tree estimation algorithm.
SOURCE CODE
function B = generatesampleCTM_fast(contexts, P, A, lengthSeq, nsamples)
%GENERATESAMPLECTM_FAST Generates samples of a context tree model.
%
% Inputs
%
%   contexts        : set of contexts
%   P               : probability distributions associated to the contexts. Each
%                     row contains the distribution of the corresponding context
%   A               : Alphabet
%   lengthSeq       : length of the sequences to be generated
%   nsamples        : number of sequences
%
% Outputs
%
%   B               : a matrix containing on each row a sequence
%
% Usage
%
%            A = [0,1,2];
%
%            ctxs = {0, [0 1], [1 1], 2}
%            P = [0,   1,   0; ...
%                  0,   0.25,   0.75;
%                  1,   0,   0;
%                  1,   0,   0 ];
%
%            B = generatesampleCTM_fast(ctxs, P, A, 100, 300);
%
%Author : Noslen Hernandez (noslen.hernandez-gonzalez@inrae.fr), Aline Duarte (alineduarte@usp.br)
%Date   : 04/2020
% initialization
B = -1*ones(nsamples, lengthSeq);
if isempty(contexts)    % generate an i.i.d sequence if contexts is empty
    for b = 1 : nsamples
        B(b,:) = samplediscretedist(A, P, lengthSeq);
    end
else
    % get the Markov process representation of the context tree model
    [past, ~, Mc, iT] = contextTree_to_FiniteMarkov(contexts, P, A);
    [npast, max_length] = size(past);
    for b = 1 : nsamples
        seq = -1*ones(1, lengthSeq);
        % initialize the sequence with a past chosen at random
        rp = randperm(npast);
        idx_last_past = rp(1);
        init_past = past(idx_last_past, :);
        seq(1 : max_length) = init_past;
        next_pos = max_length + 1;
        % add the next symbol according to the distribution given the past
        while next_pos < lengthSeq + 1
            [next_symbol, idx] = samplediscretedist(A, Mc(idx_last_past,:), 1);
            seq(next_pos) = next_symbol;
            next_pos = next_pos + 1;
            idx_last_past = iT(idx_last_past, idx);
        end
        % save the sequence
        B(b,:) = seq;
    end
end
end